basePath: /
definitions:
  abstraction.PaginationInfo:
    properties:
      count:
        type: integer
      more_records:
        type: boolean
      page:
        type: integer
      page_size:
        type: integer
      sort:
        type: string
      sort_by:
        type: string
    type: object
  dto.AuthLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.AuthLoginResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      modified_at:
        type: string
      modified_by:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      token:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - phone
    type: object
  dto.AuthLoginResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.AuthLoginResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.AuthRegisterRequest:
    properties:
      email:
        type: string
      is_active:
        type: boolean
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - phone
    type: object
  dto.AuthRegisterResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      modified_at:
        type: string
      modified_by:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - phone
    type: object
  dto.AuthRegisterResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.AuthRegisterResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.JuzCreateRequest:
    properties:
      key:
        type: string
      value:
        type: string
    required:
    - key
    - value
    type: object
  dto.JuzCreateResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      key:
        type: string
      modified_at:
        type: string
      modified_by:
        type: string
      surahs:
        description: relations
        items:
          $ref: '#/definitions/model.SurahEntityModel'
        type: array
      value:
        type: string
    required:
    - key
    - value
    type: object
  dto.JuzCreateResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.JuzCreateResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.JuzDeleteResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      key:
        type: string
      modified_at:
        type: string
      modified_by:
        type: string
      surahs:
        description: relations
        items:
          $ref: '#/definitions/model.SurahEntityModel'
        type: array
      value:
        type: string
    required:
    - key
    - value
    type: object
  dto.JuzDeleteResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.JuzDeleteResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.JuzGetByIDResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      key:
        type: string
      modified_at:
        type: string
      modified_by:
        type: string
      surahs:
        description: relations
        items:
          $ref: '#/definitions/model.SurahEntityModel'
        type: array
      value:
        type: string
    required:
    - key
    - value
    type: object
  dto.JuzGetByIDResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.JuzGetByIDResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.JuzGetResponseDoc:
    properties:
      body:
        properties:
          data:
            items:
              $ref: '#/definitions/model.JuzEntityModel'
            type: array
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  dto.JuzUpdateRequest:
    properties:
      id:
        type: integer
      key:
        type: string
      value:
        type: string
    required:
    - id
    - key
    - value
    type: object
  dto.JuzUpdateResponse:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      key:
        type: string
      modified_at:
        type: string
      modified_by:
        type: string
      surahs:
        description: relations
        items:
          $ref: '#/definitions/model.SurahEntityModel'
        type: array
      value:
        type: string
    required:
    - key
    - value
    type: object
  dto.JuzUpdateResponseDoc:
    properties:
      body:
        properties:
          data:
            $ref: '#/definitions/dto.JuzUpdateResponse'
          meta:
            $ref: '#/definitions/response.Meta'
        type: object
    type: object
  model.SurahEntityModel:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      key:
        type: string
      modified_at:
        type: string
      modified_by:
        type: string
      juz_id:
        description: relations
        type: integer
      value:
        type: string
    required:
    - key
    - value
    type: object
  model.JuzEntityModel:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      id:
        type: integer
      key:
        type: string
      modified_at:
        type: string
      modified_by:
        type: string
      surahs:
        description: relations
        items:
          $ref: '#/definitions/model.SurahEntityModel'
        type: array
      value:
        type: string
    required:
    - key
    - value
    type: object
host: localhost:3030
info:
  contact: {}
  description: This is a doc for Quran.
  title: quran
  version: 0.0.1
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthLoginResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthRegisterResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Register user
      tags:
      - auth
  /juzs:
    get:
      consumes:
      - application/json
      description: Get juzs
      parameters:
      - in: query
        name: created_at
        type: string
      - in: query
        name: created_by
        type: string
      - in: query
        name: key
        type: string
      - in: query
        name: modified_at
        type: string
      - in: query
        name: modified_by
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: sort
        type: string
      - in: query
        name: sort_by
        type: string
      - in: query
        name: value
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JuzGetResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Get juzs
      tags:
      - juzs
    post:
      consumes:
      - application/json
      description: Create juzs
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.JuzCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JuzCreateResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Create juzs
      tags:
      - juzs
  /juzs/{id}:
    delete:
      consumes:
      - application/json
      description: Delete juzs
      parameters:
      - description: id path
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JuzDeleteResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Delete juzs
      tags:
      - juzs
    patch:
      consumes:
      - application/json
      description: Update juzs
      parameters:
      - description: id path
        in: path
        name: id
        required: true
        type: integer
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.JuzUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JuzUpdateResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Update juzs
      tags:
      - juzs
  /juzs/{id}/{child}/{child_id}:
    get:
      consumes:
      - application/json
      description: Get juzs by id
      parameters:
      - description: id path
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.JuzGetByIDResponseDoc'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.errorResponse'
      security:
      - BearerAuth: []
      summary: Get juzs by id
      tags:
      - juzs
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
